[package]
name = "zippa"
version = "0.1.0"
edition = "2021"
authors = ["Baba Ali"]
exclude = ["*.zip", "sample/*"]

[dependencies]
clap = {version = "3.1.6", features = ["derive"]}
zip = "0.6.3"
tempfile = "3.2.0"

